[package]
name = "krata-xenevtchn"
version.workspace = true
edition = "2021"
resolver = "2"

[dependencies]
libc = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
nix = { workspace = true, features = ["ioctl"] }
tokio = { workspace = true }

[lib]
name = "xenevtchn"

[[example]]
name = "xenevtchn-simple"
path = "examples/simple.rs"
