[pre-commit]
parallel = true

[pre-commit.commands.build]
run = "./scripts/cargo.sh build"

[pre-commit.commands.test]
run = "./scripts/cargo.sh test"

[pre-commit.commands.fmt]
run = "./scripts/cargo.sh fmt --all -- --check"

[pre-commit.commands.clippy]
run = "./scripts/cargo.sh clippy"
