[package]
name = "krata-xenclient"
description = "An implementation of Xen userspace for krata."
license.workspace = true
version.workspace = true
homepage.workspace = true
repository.workspace = true
edition = "2021"
resolver = "2"

[dependencies]
elf = { workspace = true }
flate2 = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
krata-xencall = { path = "../xencall", version = "0.0.1" }
krata-xenstore = { path = "../xenstore", version = "0.0.1" }
memchr = { workspace = true }
slice-copy = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
xz2 = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }

[lib]
name = "xenclient"

[[example]]
name = "xenclient-boot"
path = "examples/boot.rs"
