[package]
name = "krata-xenclient"
version.workspace = true
edition = "2021"
resolver = "2"

[dependencies]
elf = { workspace = true }
flate2 = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
krata-xencall = { path = "../xencall" }
krata-xenstore = { path = "../xenstore" }
memchr = { workspace = true }
slice-copy = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
xz2 = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }

[lib]
name = "xenclient"

[[example]]
name = "xenclient-boot"
path = "examples/boot.rs"
