[package]
name = "krata-runtime"
version.workspace = true
edition = "2021"
resolver = "2"

[dependencies]
advmac = { workspace = true }
anyhow = { workspace = true }
backhand = { workspace = true }
ipnetwork = { workspace = true }
krata = { path = "../krata" }
krata-oci = { path = "../oci" }
log = { workspace = true }
loopdev-3 = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
krata-xenclient = { path = "../xen/xenclient" }
krata-xenevtchn = { path = "../xen/xenevtchn" }
krata-xengnt = { path = "../xen/xengnt" }
krata-xenstore = { path = "../xen/xenstore" }

[lib]
name = "kratart"

[dev-dependencies]
env_logger = { workspace = true }

[[example]]
name = "kratart-squashify"
path = "examples/squashify.rs"

[[example]]
name = "kratart-channel"
path = "examples/channel.rs"
