[package]
name = "krata-xengnt"
version.workspace = true
edition = "2021"
resolver = "2"

[dependencies]
thiserror = { workspace = true }
libc = { workspace = true }
nix = { workspace = true, features = ["ioctl"] }

[lib]
name = "xengnt"
