[package]
name = "xenevtchn"
version.workspace = true
edition = "2021"
resolver = "2"

[dependencies]
log = { workspace = true }

[dependencies.nix]
workspace = true
features = ["ioctl"]

[lib]
path = "src/lib.rs"

[[example]]
name = "xenevtchn-simple"
path = "examples/simple.rs"
