name: check
on: [push, pull_request]
jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - run: ./hack/ci/install-linux-deps.sh
    - run: ./hack/build/cargo.sh fmt --all -- --check
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./hack/code/shellcheck.sh
