name: check
on: [push, pull_request]
jobs:
  build:
    name: cargo build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: ./scripts/ci/install-deps.sh
    - run: ./scripts/build/cargo.sh build
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: ./scripts/ci/install-deps.sh
    - run: ./scripts/build/cargo.sh test
  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - run: ./scripts/ci/install-deps.sh
    - run: ./scripts/build/cargo.sh clippy
  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - run: ./scripts/ci/install-deps.sh
    - run: ./scripts/build/cargo.sh fmt --all -- --check
  initrd:
    name: initrd
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: "x86_64-unknown-linux-gnu,x86_64-unknown-linux-musl"
    - run: ./scripts/ci/install-deps.sh
    - run: ./scripts/initrd/build.sh
