name: kernel
on:
  push:
    paths:
    - "kernel/**"
    - "hack/ci/**"
  pull_request:
    paths:
    - "kernel/**"
    - "hack/ci/**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
        - x86_64
        - aarch64
    env:
      TARGET_ARCH: "${{ matrix.arch }}"
    name: build ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: dtolnay/rust-toolchain@stable
    - run: ./hack/ci/install-linux-deps.sh
    - run: ./hack/kernel/build.sh
      env:
        KRATA_KERNEL_BUILD_JOBS: "5"
