name: nightly
on:
  workflow_dispatch:
  schedule:
  - cron: "0 4 * * *"
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: "x86_64-unknown-linux-gnu,x86_64-unknown-linux-musl"
    - run: ./scripts/ci/install-deps.sh
    - run: ./scripts/bundle.sh
    - uses: actions/upload-artifact@v4
      with:
        name: krata-nightly-x86_64
        path: target/bundle/krata.tgz
        compression-level: 0
