name: os
on:
  push:
    paths:
    - "os/**"
    - "hack/os/**"
    - "hack/ci/**"
  pull_request:
    paths:
    - "os/**"
    - "hack/os/**"
    - "hack/ci/**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
        - x86_64
        - aarch64
    env:
      TARGET_ARCH: "${{ matrix.arch }}"
    name: build ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: "${{ matrix.arch }}-unknown-linux-gnu,${{ matrix.arch }}-unknown-linux-musl"
    - run: ./hack/ci/install-linux-deps.sh
    - run: ./hack/os/build.sh
      env:
        KRATA_KERNEL_BUILD_JOBS: "5"
    - uses: actions/upload-artifact@v4
      with:
        name: krata-os-${{ matrix.arch }}
        path: "target/os/krata-${{ matrix.arch }}.qcow2"
        compression-level: 0
