name: os
on:
  push:
    paths:
    - "os/**"
  pull_request:
    paths:
    - "os/**"
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./hack/ci/install-deps.sh
    - run: ./hack/os/build.sh
      env:
        KRATA_KERNEL_BUILD_JOBS: "5"
