name: os
on:
  push:
    paths:
    - "os/**"
    - "hack/os/**"
  pull_request:
    paths:
    - "os/**"
    - "hack/os/**"
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: "x86_64-unknown-linux-gnu,x86_64-unknown-linux-musl"
    - run: ./hack/ci/install-deps.sh
    - run: ./hack/os/build.sh
      env:
        KRATA_KERNEL_BUILD_JOBS: "5"
    - uses: actions/upload-artifact@v4
      with:
        name: krata-os-x86_64
        path: "target/os/krata.qcow2"
        compression-level: 0
  