name: release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - release-test

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release-plz:
    name: release-plz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - name: release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
